platform :ios, '7.0'
pod 'AutoScrollLabel'
pod 'SuProgress'
pod 'DKNavbarBackButton', :git => 'https://github.com/wade0n/DKNavbarBackButton.git', :branch => 'master'
pod 'ARChromeActivity'
pod 'ARSafariActivity'
